[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.buildCommand]
value = "pip install -r requirements.txt"

[build.watchPatterns]
value = ["**/*.py", "**/*.html", "requirements.txt"]
